export const MOVES = {
  // --- Punch Strings ---
  PUNCH_1: {
    name: 'Swift Jab',
    startup: 6,
    active: 5,
    recovery: 10,
    damage: 35,
    stunFrames: 14,
    knockback: { x: 90, y: 0 },
    hitbox: { offsetX: 55, offsetY: -80, w: 45, h: 30 },
    height: 'MID',
    isHeavy: false,
  },
  PUNCH_2: {
    name: 'Dao Slash',
    startup: 7,
    active: 6,
    recovery: 12,
    damage: 45,
    stunFrames: 16,
    knockback: { x: 120, y: 0 },
    hitbox: { offsetX: 65, offsetY: -75, w: 55, h: 35 },
    height: 'MID',
    isHeavy: false,
  },
  PUNCH_3: {
    name: 'Dual Crescent Cleave',
    startup: 11,
    active: 7,
    recovery: 18,
    damage: 65,
    stunFrames: 24,
    knockback: { x: 220, y: -60 },
    hitbox: { offsetX: 75, offsetY: -85, w: 65, h: 45 },
    height: 'MID',
    isHeavy: true,
  },
  PUNCH_FORWARD: {
    name: 'Piercing Lunging Thrust',
    startup: 10,
    active: 6,
    recovery: 16,
    damage: 70,
    stunFrames: 22,
    lungeSpeed: 280,
    knockback: { x: 260, y: -40 },
    hitbox: { offsetX: 90, offsetY: -75, w: 75, h: 32 },
    height: 'MID',
    isHeavy: true,
  },
  PUNCH_UP: {
    name: 'Rising Dragon Uppercut',
    startup: 8,
    active: 8,
    recovery: 20,
    damage: 75,
    stunFrames: 26,
    knockback: { x: 100, y: -380 },
    hitbox: { offsetX: 50, offsetY: -120, w: 60, h: 70 },
    height: 'HIGH',
    isHeavy: true,
  },
  PUNCH_DOWN: {
    name: 'Low Twin Poke',
    startup: 8,
    active: 6,
    recovery: 13,
    damage: 40,
    stunFrames: 15,
    knockback: { x: 80, y: 0 },
    hitbox: { offsetX: 60, offsetY: -25, w: 55, h: 25 },
    height: 'LOW',
    isHeavy: false,
  },

  // --- Kick Strings ---
  KICK_1: {
    name: 'Snap Kick',
    startup: 7,
    active: 5,
    recovery: 12,
    damage: 40,
    stunFrames: 15,
    knockback: { x: 100, y: 0 },
    hitbox: { offsetX: 60, offsetY: -70, w: 50, h: 30 },
    height: 'MID',
    isHeavy: false,
  },
  KICK_2: {
    name: 'High Roundhouse',
    startup: 9,
    active: 6,
    recovery: 15,
    damage: 55,
    stunFrames: 20,
    knockback: { x: 160, y: -40 },
    hitbox: { offsetX: 70, offsetY: -95, w: 60, h: 40 },
    height: 'HIGH',
    isHeavy: false,
  },
  KICK_FORWARD: {
    name: 'Flying Torpedo Kick',
    startup: 12,
    active: 8,
    recovery: 20,
    damage: 80,
    stunFrames: 26,
    lungeSpeed: 360,
    knockback: { x: 280, y: -120 },
    hitbox: { offsetX: 85, offsetY: -75, w: 70, h: 40 },
    height: 'MID',
    isHeavy: true,
  },
  KICK_UP: {
    name: 'Descending Axe Kick',
    startup: 13,
    active: 6,
    recovery: 22,
    damage: 85,
    stunFrames: 28,
    knockback: { x: 120, y: 200 },
    hitbox: { offsetX: 60, offsetY: -105, w: 65, h: 60 },
    height: 'HIGH',
    isHeavy: true,
  },
  KICK_DOWN: {
    name: 'Dragon Sweep',
    startup: 10,
    active: 6,
    recovery: 17,
    damage: 50,
    stunFrames: 35,
    knockback: { x: 140, y: -150 },
    hitbox: { offsetX: 70, offsetY: -15, w: 75, h: 25 },
    height: 'LOW',
    isHeavy: true,
    isKnockdown: true,
  },

  // --- Dedicated Heavy Attack (I / B key or HEAVY touch button) ---
  HEAVY_SMASH: {
    name: 'Mountain Splitter',
    startup: 14,
    active: 6,
    recovery: 26,
    damage: 105,
    stunFrames: 32,
    knockback: { x: 340, y: -170 },
    hitbox: { offsetX: 80, offsetY: -85, w: 80, h: 45 },
    height: 'MID',
    isHeavy: true,
  },

  // --- Ranged Attack ---
  RANGED_THROW: {
    name: 'Shadow Kunai',
    startup: 14,
    active: 4,
    recovery: 18,
    damage: 45,
    stunFrames: 18,
    hitbox: null, // spawns projectile
    height: 'MID',
    isHeavy: false,
  },

  // --- Shadow Form Moves ---
  SHADOW_ERUPTION: {
    name: 'Shadow Eruption',
    startup: 12,
    active: 14,
    recovery: 24,
    damage: 130,
    stunFrames: 40,
    knockback: { x: 120, y: -440 },
    hitbox: { offsetX: 110, offsetY: -60, w: 140, h: 140 },
    height: 'MID',
    isHeavy: true,
    isShadow: true,
  },
  SHADOW_DASH: {
    name: 'Void Flash Piercer',
    startup: 8,
    active: 10,
    recovery: 20,
    damage: 150,
    stunFrames: 45,
    lungeSpeed: 650,
    knockback: { x: 300, y: -200 },
    hitbox: { offsetX: 100, offsetY: -70, w: 120, h: 60 },
    height: 'MID',
    isHeavy: true,
    isShadow: true,
  }
};
